[package]
name = 'powdermilk-biscuits'
version = '0.1.0'
edition = '2021'
build = 'build.rs'

[features]
default = ['wgpu']
output-spirv = []
empty-backend = []
gl = ['glow', 'glam', 'glutin']
wgpu = ['dep:wgpu', 'winit', 'futures']

[dependencies]
rand = '0.8.5'
evc_derive = { path = 'evc_derive' }
image = '0.24.2'
bspline = '1.1.0'
lyon = '1.0.0'
bincode = '1.3.3'
serde = { version = '*', features = ['derive'] }
flate2 = '1.0.24'
rfd = { path = 'rfd' }
glow = { version = '0.11.2', optional = true }
glam = { version = '0.21.2', optional = true }
wgpu = { version = '0.13.1', optional = true }
winit = { path = 'winit2', optional = true }
futures = { version = '0.3.21', optional = true }

[target.'cfg(windows)'.dependencies.glutin]
path = 'glutin/glutin'
default-features = false
optional = true

[target.'cfg(unix)'.dependencies.glutin]
path = 'glutin/glutin'
default-features = false
features = ['x11']
optional = true

[profile.dev]
incremental = true

[profile.release]
incremental = true
