[package]
name = 'tablet-thing'
version = '0.1.0'
edition = '2021'
build = 'build.rs'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = '0.8.5'
evc_derive = { path = 'evc_derive' }
image = '0.24.2'
bspline = '1.1.0'
glow = { version = '0.11.2' }
lyon = '1.0.0'
glam = '0.21.2'
bincode = '1.3.3'
serde = { version = '*', features = ['derive'] }
flate2 = '1.0.24'

[features]
default = []
output-spirv = []

[target.'cfg(windows)'.dependencies.glutin]
path = 'glutin/glutin'
default-features = false

[target.'cfg(unix)'.dependencies.glutin]
path = 'glutin/glutin'
default-features = false
features = ['x11']

#winit = { path = 'winit2' }
#vulkano = { path = 'vulkano/vulkano' }
#vulkano-win = { path = 'vulkano/vulkano-win' }
#vulkano-shaders = { path = 'vulkano/vulkano-shaders' }

#[target.'cfg(windows)'.dependencies.windows]
#version = '0.37.0'
#features = [
#    'alloc',
#    'implement',
#    'Win32_Foundation',
#    'Win32_System_Com',
#    'Win32_UI_TabletPC',
#    'Win32_Graphics_Gdi',
#    'Win32_System_LibraryLoader',
#    'Win32_UI_WindowsAndMessaging',
#    'Win32_UI_Input_KeyboardAndMouse',
#]

