[workspace]
resolver = '2'
members = [
    'pmb',
    'pmb-gl',
    'pmb-wgpu',
    'derive-pmb-loop',
    'derive-disk',
]

[profile.dev]
incremental = true

[profile.release]
incremental = true
debug = true
