[workspace]
resolver = '2'
members = [
    'pmb',
    'pmb-tess',
    'pmb-gl',
    'pmb-wgpu',
    'pmb-piet',
    'derive-disk',
    'derive-evc',
]

[profile.dev]
incremental = true

[profile.release]
incremental = true
debug = true
