[workspace]
resolver = '2'
members = [
    'pmb',
    'backend-gl',
    'backend-wgpu',
    'derive-loop',
    'derive-disk',
]

[profile.dev]
incremental = true

[profile.release]
incremental = true
debug = true
