[package]
name = 'egui-wgpu'
version = '0.1.0'
edition = '2021'

[dependencies.egui]
git = 'https://github.com/zphixon/egui'
branch = 'my-winit'
package = 'egui'

[dependencies.egui-winit]
git = 'https://github.com/zphixon/egui'
branch = 'my-winit'
package = 'egui-winit'
