[package]
name = 'derive-loop'
version = '0.1.0'
edition = '2021'

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
derive_builder = '0.11.2'
indexmap = '1.9.1'
