[package]
name = 'pmb-util'
version = '0.1.0'
rust-version = '1.64.0'
edition = '2021'

[dependencies]
tracing-subscriber.workspace = true
gumdrop.workspace = true
anyhow.workspace = true
paste.workspace = true
powdermilk-biscuits.workspace = true
