[package]
name = 'pmb-macros'
version = '0.1.0'
edition = '2021'

[lib]
proc-macro = true


[dependencies]
proc-macro2 = '1.0.42'
quote = '1.0.21'
syn = '1.0.101'
derive_builder = '0.11.2'
indexmap = '1.9.1'
