name: push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: build cache
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - uses: actions/cache@v3
        name: deps cache
        id: cache-deps
        with:
          path: |
            ~/.cargo/bin/
            apt/*.deb
          key: ${{ runner.os }}-deps

      - name: install gtk/glslang/naga
        if: '!steps.cache-deps.outputs.cache-hit'
        run: |
          sudo apt install --download-only glslang-tools build-essential libgtk-3-dev
          mkdir -p apt
          cp /var/cache/apt/archives/*.deb apt
          sudo apt install glslang-tools build-essential libgtk-3-dev
          cargo install naga-cli

      - name: unpack gtk/glslang
        if: 'steps.cache-deps.outputs.cache-hit'
        run: |
          sudo cp apt/*.deb /var/cache/apt/archives/
          sudo apt install glslang-tools build-essential libgtk-3-dev

      - name: check shader compilers are working
        run: |
          naga backend-wgpu/src/shaders/stroke_mesh.wgsl
          glslangValidator backend-gl/src/shaders/stroke_line.vert

      - name: test
        run: cargo test

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: build cache
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - uses: actions/cache@v3
        name: deps cache
        id: cache-deps
        with:
          path: |
            C:\glslang\
            ~/.cargo/bin/
          key: ${{ runner.os }}-deps

      - name: download glslang/naga
        if: '!steps.cache-deps.outputs.cache-hit'
        run: |
          Invoke-WebRequest -URI https://ci.appveyor.com/api/buildjobs/nweuuamas19eil5c/artifacts/build%2Finstall%2Fglslang-master-windows-x64-Release.zip -OutFile glslang.zip
          7z x glslang.zip -oC:\glslang
          cargo install naga-cli

      - name: check shader compilers
        run: |
          Add-Content $env:GITHUB_PATH 'C:\glslang\bin'
          $env:Path += ';C:\glslang\bin'
          glslangValidator backend-gl/src/shaders/stroke_line.vert
          naga backend-wgpu/src/shaders/stroke_mesh.wgsl

      - name: test
        run: cargo test

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: build cache
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - uses: actions/cache@v3
        name: deps cache
        id: cache-deps
        with:
          path: |
            /usr/local/Cellar/glslang/*
            ~/.cargo/bin/
          key: ${{ runner.os }}-deps

      - name: install glslang/naga
        if: '!steps.cache-deps.outputs.cache-hit'
        run: |
          cargo install naga-cli
          brew install glslang

      - name: link glslang
        if: 'steps.cache-deps.outputs.cache-hit'
        run: brew link glslang

      - name: check shader compilers are working
        run: |
          naga backend-wgpu/src/shaders/stroke_mesh.wgsl
          glslangValidator backend-gl/src/shaders/stroke_line.vert

      - name: test
        run: cargo test
