name: push
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo
      - name: glslang/gtk3
        run: sudo apt install glslang-tools build-essential libgtk-3-dev
      - name: naga
        continue-on-error: true
        run: cargo install naga-cli
      - name: check shader compilers are working
        run: |
          naga backend-wgpu/src/shaders/stroke_mesh.wgsl
          glslangValidator backend-gl/src/shaders/stroke_line.vert
      - name: check
        run: cargo check --all-targets
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo
      - name: install/check naga/glslang
        run: |
          Invoke-WebRequest -URI https://ci.appveyor.com/api/buildjobs/nweuuamas19eil5c/artifacts/build%2Finstall%2Fglslang-master-windows-x64-Release.zip -OutFile glslang.zip
          7z x glslang.zip -oC:\glslang
          $env:Path += ';C:\glslang\bin'
          Add-Content $env:GITHUB_PATH 'C:\glslang\bin'
          glslangValidator backend-gl/src/shaders/stroke_line.vert
          cargo install naga-cli
          naga backend-wgpu/src/shaders/stroke_mesh.wgsl
      - name: check
        run: cargo check --all-targets
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo
      - name: glslang
        run: brew install glslang
      - name: naga
        continue-on-error: true
        run: cargo install naga-cli
      - name: check shader compilers are working
        run: |
          naga backend-wgpu/src/shaders/stroke_mesh.wgsl
          glslangValidator backend-gl/src/shaders/stroke_line.vert
      - name: check
        run: cargo check --all-targets
