name: Rust

on:
  push:
    tags: [ "prerelease-**" ]
  pull_request:
    branches: [ "main", "prerelease-**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: shaderc and naga
        run: sudo apt install glslang-tools build-essential libgtk-3-dev && cargo install naga-cli
      - name: check shader compilers are working
        run: |
          naga backend-wgpu/src/shaders/stroke_mesh.wgsl
          glslangValidator backend-gl/src/shaders/stroke_line.vert
      - name: build
        run: CARGO_PROFILE_RELEASE_DEBUG=false cargo build --release --features pmb-release
      - name: gl backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-gl-linux
          path: target/release/backend-gl
      - name: wgpu backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-wgpu-linux
          path: target/release/backend-wgpu
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: install/check naga/glslang
        run: |
          Invoke-WebRequest -URI https://ci.appveyor.com/api/buildjobs/nweuuamas19eil5c/artifacts/build%2Finstall%2Fglslang-master-windows-x64-Release.zip -OutFile glslang.zip
          7z x glslang.zip -oC:\glslang
          $env:Path += ';C:\glslang\bin'
          Add-Content $env:GITHUB_PATH 'C:\glslang\bin'
          glslangValidator backend-gl/src/shaders/stroke_line.vert
          cargo install naga-cli
          naga backend-wgpu/src/shaders/stroke_mesh.wgsl
      - name: build
        run: |
          $env:CARGO_PROFILE_RELEASE_DEBUG = 'false'
          cargo build --release --features pmb-release
      - name: gl backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-gl-win-msvc.exe
          path: target/release/backend-gl.exe
      - name: wgpu backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-wgpu-win-msvc.exe
          path: target/release/backend-wgpu.exe
  ## TODO
  #macos:
  #  runs-on: macos-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: shaderc and naga
  #      run: brew install glslang && cargo install naga-cli
  #    - name: check shader compilers are working
  #      run: |
  #        naga backend-wgpu/src/shaders/stroke_mesh.wgsl
  #        glslangValidator backend-gl/src/shaders/stroke_line.vert
  #    - name: build
  #      run: CARGO_PROFILE_RELEASE_DEBUG=false cargo build --release --features pmb-release
  #    - name: gl backend artifact
  #      uses: actions/upload-artifact@v3
  #      with:
  #        name: backend-gl-macos
  #        path: target/release/backend-gl
  #    - name: wgpu backend artifact
  #      uses: actions/upload-artifact@v3
  #      with:
  #        name: backend-wgpu-macos
  #        path: target/release/backend-wgpu
