name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: shaderc and naga
      run: sudo apt install glslang-tools build-essential libgtk-3-dev mold && cargo install naga-cli
    - name: -Z minimal-versions
      run: cargo test --verbose -Z minimal-versions
    - name: --locked
      run: cargo test --verbose --locked
    - name: rm Cargo.lock
      run: rm Cargo.lock && cargo test
